### ISSUE TITLE
user profile + home page - fejvadasz

### ISSUE THREAD

**Issue by oviola01** [HeadHunterApp/HeadHunter#17]
Below pages after login as fejvadasz.
- [x] home page
- [x] show profile
- [x] edit profile

**Comment by oviola01** [comment]
![fejv_kezdo](https://github.com/HeadHunterApp/HeadHunter/assets/69991534/62424626-5037-4aa3-804a-0bc96abbba63)
![fejv_profil](https://github.com/HeadHunterApp/HeadHunter/assets/69991534/ecfe87e6-2aad-4fb1-befb-16ad2569954a)

**Comment by marybogyo** [comment]
Fényképfeltöltés/módosítás rendben, adatok módosítása/feltöltése rendben.
Jelszó módosítást a fejlesztendőbe tenni.
