### ISSUE TITLE
create maintables

### ISSUE THREAD

**Issue by oviola01** [HeadHunterApp/HeadHunter#2]
Creation of tables which have no parents:

- [x] user
- [x] munkaltato
- [x] fejvadasz
- [x] allaskereso
- [x] terulet
- [x] nyelvtudas
- [x] vegzettseg
- [x] szakmai_ismeret
- [x] tapasztalat_ido

**Comment by oviola01** [comment]
User kész, route-ok még hiányoznak. Jogosultsag mező értéke elérési út feltételén alapszik, így szerintem a route-ban kell majd ezt megadni - emiatt ez később kerül majd bele, egyelőre nincs jelentősége.
@marybogyo , kérlek tedd bele a Fejvadasz és az Allaskereso táblák modeljét, migrációs fájlját és controllerét.

**Comment by marybogyo** [comment]
#11

**Comment by oviola01** [comment]
[#22 ](https://github.com/HeadHunterApp/HeadHunter/pull/22)
