### ISSUE TITLE
create child tables

### ISSUE THREAD

**Issue by oviola01** [HeadHunterApp/HeadHunter#3]
- [x] Pozicio
- [x] Allas
- [x] Allas_ismeret
- [x] Allas_nyelvtudas
- [x] Allas_vegzettseg
- [x] Allas_tapasztalat
- [x] Fejvadasz_terulet
- [x] Allaskereso_ismeret
- [x] Allaskereso_nyelvtudas
- [x] Allaskereso_tapasztalat
- [x] Allaskereso_tanulmany

**Comment by marybogyo** [comment]
#23
